revoke execute on function public.has_role(uuid, public.app_role) from public, anon;
revoke execute on function public.is_project_member(uuid, uuid) from public, anon;
revoke execute on function public.is_project_owner(uuid, uuid) from public, anon;
revoke execute on function public.shares_project(uuid, uuid) from public, anon;
revoke execute on function public.session_project(uuid) from public, anon;
revoke execute on function public.story_project(uuid) from public, anon;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
grant execute on function public.has_role(uuid, public.app_role) to authenticated;
grant execute on function public.is_project_member(uuid, uuid) to authenticated;
grant execute on function public.is_project_owner(uuid, uuid) to authenticated;
grant execute on function public.shares_project(uuid, uuid) to authenticated;
grant execute on function public.session_project(uuid) to authenticated;
grant execute on function public.story_project(uuid) to authenticated;